# This is a basic workflow to help you get started with Actions

name: CD-sites

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled?'     
        required: false
        default: 'false'
      vcell_version:
        description: 'version.major.minor' 
        required: true
        default: '7.4.0'
      vcell_build:
        description: 'build number'
        required: true
        default: '23'
      vcell_site:
        description: 'rel or alpha'
        required: true
        default: 'alpha'
      server_only:
        description: 'Deploy only the server components?'
        required: true
        default: 'false'
      commit_hash:
        description: sha hash of commit to be deployed
        required: true
        default: 'bdea85b98a40035e05c1d1531f689a4f167ad93c'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit_hash }}
        fetch-depth: 0
    - name: setup global environment variables
      shell: bash 
      run: |
        echo "VCELL_VERSION=${{ github.event.inputs.vcell_version }}" >> $GITHUB_ENV
        echo "VCELL_BUILD=${{ github.event.inputs.vcell_build }}" >> $GITHUB_ENV
        echo "VCELL_SITE=${{ github.event.inputs.vcell_site }}" >> $GITHUB_ENV
        echo "VCELL_TAG=`git rev-parse HEAD | cut -c -7`" >> $GITHUB_ENV
        echo "VCELL_REPO_NAMESPACE=ghcr.io/virtualcell" >> $GITHUB_ENV
        if [ "${{ github.event.inputs.vcell_site }}" == "rel" ]; then\
        	echo "MANAGER_NODE=vcellapi.cam.uchc.edu" >> $GITHUB_ENV;\
        	echo "VCELL_INSTALLER_REMOTE_DIR="/share/apps/vcell3/apache_webroot/htdocs/webstart/Rel"" >> $GITHUB_ENV;\
        else if [ "${{ github.event.inputs.vcell_site }}" == "alpha" ]; then\
         	echo "MANAGER_NODE=vcellapi-beta.cam.uchc.edu" >> $GITHUB_ENV;\
        	echo "VCELL_INSTALLER_REMOTE_DIR="/share/apps/vcell3/apache_webroot/htdocs/webstart/Alpha"" >> $GITHUB_ENV;\
        else echo "Uknown site name ${{ github.event.inputs.vcell_site }}"; exit 1; fi; fi
    - name: setup config and build
      shell: bash
      run: |
        env
        cd docker/swarm
        export "VCELL_CONFIG_FILE_NAME=server_${VCELL_SITE}_${VCELL_VERSION}_${VCELL_BUILD}_${VCELL_TAG}.config"
        echo "VCELL_CONFIG_FILE_NAME=$VCELL_CONFIG_FILE_NAME" >> GITHUB_ENV
        ./serverconfig-uch.sh $VCELL_SITE $VCELL_REPO_NAMESPACE $VCELL_TAG $VCELL_VERSION $VCELL_BUILD $VCELL_CONFIG_FILE_NAME
        sudo docker login -u ${{ secrets.ACTION_USER }} -p ${{ secrets.ACTION_TOKEN }} ghcr.io
        sudo docker pull $VCELL_REPO_NAMESPACE/vcell-clientgen:$VCELL_TAG
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session 2
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
